### PR TITLE
Full support for 'emmeans'

### PR DESCRIPTION
**Pull request by paul-buerkner**
This PR enables full support of the emmeans package (#418) thanks to the help of @rvlenth.

@rvlenth would you mind running a few tests with the new code before I merge this PR?

Thanks again for your help!

### CODE REVIEW

**Comment by rvlenth** [comment]
I'd be happy to test some things, but am not a power user of **brms**. I am curious to see if ordinal models are supported to the degree needed; same with hurdle and zip models. I'll see if I can muddle through some tests to see. 

Also, a kinda dumb question that shows my git cluelessness -- is there a way I can merge this PR with your changes and extensions into my own fork of brms? I can't really test what you have without doing that, or manually copying the changed files.

Any particular reason for suggesting emmeans >= 1.4.2?

Are there particular things you have in mind that you'd like to see me test?

**Comment by paul-buerkner** [comment]
Thank you! ordinal and hurdle etc. models should be supported. You can use the `dpar` argument to select the chosen parameter if required for hurdle and similar models.

I am not a git expert either but I would expect it would make most sense if you would update your brms fork from my brms repo and then merge the emmeans branch of brms into yours. For the former part not sure how this is exactly realized.

No specific reason for 1.4.2 I guess that was just the one I appeared to have on my machine. Would you recommend a specific version requirement?

If you could run an ordinal and a hurdle model and check whether the results match your expectation, that would be perfect! I am not a regular emmeans user so I don't know what behavior you would expect in those cases.

**Comment by rvlenth** [comment]
On github stuff, hmmm. There are only 7 files, so maybe the simplest thing is for me to just manually copy the code!

Very early report: I did this to get some examples:
```r
fitj <- rename_pars(brms:::brmsfit_examplej)      # for j = 1,2,...,6
```
and so far, doing `emmeans::ref_grid(fitj)` works only for `fit1` and `fit3`. Perhaps it'll be better when I upgrade to your version of the code.

**Comment by paul-buerkner** [comment]
I just fixed some problems so that now all example fit models in brms can be run (perhaps by using the `resp`, `dpar` and `nlpar` arguments). 

You can also just install brms from github via `remotes::install_github("paul-buerkner/brms", ref = "emmeans")` so that you don't need to copy over any code.

**Pull request merged**
