### PR TITLE
Generalize emmeans support

### PR DESCRIPTION
**Pull request by paul-buerkner**
This PR closes issues #907 and #1134. @mattansb would you mind reviewing this PR and also run some of your own tests to check that everything works well? What is more, emmeans with brms models can now also handle marginalization over varying effects which essentially implements #489.

### CODE REVIEW

**Comment by mattansb** [comment]
Sure, I'll give this a look over the next couple of days (:

**Comment by paul-buerkner** [comment]
Thanks! Actually, they may not be the requirement for a review but I would appreciate if you could run some tests. I will just merge this PR now and if there are some problems coming up in your tests, we can still fix them before the next official release. Thanks again for your help on these features!

**Comment by mattansb** [comment]
Ran some quick tests I could think of:
- Only recover "fixed" effects ✅
- How are multiple intercepts dealt with in ordinal models? (output is weird?) ❓ 
- Support of multivariate emmeans ❌(but do we care?)

``` r
library(brms)
library(emmeans)
```

##  Only recover "fixed" effects

``` r
data("mtcars")
m1 <- brm(mpg ~ cyl + (hp|gear), data = mtcars,
          chains = 2, iter = 200, refresh = 0)
```

Seems good - only recovers terms of fixed effects.

``` r
recover_data(m1) |> head()
#>                   cyl
#> Mazda RX4           6
#> Mazda RX4 Wag       6
#> Datsun 710          4
#> Hornet 4 Drive      6
#> Hornet Sportabout   8
#> Valiant             6
```

## multiple intercepts / ordinal models

<https://cran.r-project.org/web/packages/emmeans/vignettes/sophisticated.html#ordinal>

``` r
mtcars$cyl <- factor(mtcars$cyl, ordered = TRUE)
m2 <- brm(cyl ~ mpg + am, data = mtcars, family = cumulative(),
          chains = 2, iter = 200, refresh = 0)

ref_grid(m2)
#> 'emmGrid' object with variables:
#>     mpg = 20.091
#>     am = 0, 1
#> Transformation: "logit"
```
Compare to `ordinal::clm()` - the various "modes" are not supported by `brms`.

```R
m2F <- ordinal::clm(cyl ~ mpg + am, data = mtcars)

ref_grid(m2F)
#> 'emmGrid' object with variables:
#>     mpg = 20.091
#>     am = 0, 1
ref_grid(m2F, mode = "linear.predictor")
#> 'emmGrid' object with variables:
#>     mpg = 20.091
#>     am = 0, 1
#>     cut = multivariate response levels: 4|6, 6|8       # cut is a stand in for the multiple intercepts.
#> Transformation: "logit"
ref_grid(m2F, mode = "exc.prob")
#> 'emmGrid' object with variables:
#>     mpg = 20.091
#>     am = 0, 1
#>     cut = multivariate response levels: 4|6, 6|8
ref_grid(m2F, mode = "prob")
#> 'emmGrid' object with variables:
#>     mpg = 20.091
#>     am = 0, 1
#>     cyl = multivariate response levels: 4, 6, 8
ref_grid(m2F, mode = "mean.class")
#> 'emmGrid' object with variables:
#>     mpg = 20.091
#>     am = 0, 1
```

### Compare emmeans

This gives very different results (because of the short chains?) - neither of the "modes" give the same result as `brms`...

``` r
emmeans(m2, ~am)
#>  am emmean lower.HPD upper.HPD
#>   0  -34.7     -65.8     -15.0
#>   1  -34.6     -62.7     -12.4
#> 
#> Point estimate displayed: median 
#> Results are given on the logit (not the response) scale. 
#> HPD interval probability: 0.95
```

Compared to this:

``` r
emmeans(m2F, ~ am)
#>  am emmean    SE  df asymp.LCL asymp.UCL
#>   0 -0.284 0.796 Inf     -1.84      1.27
#>   1 -0.383 1.172 Inf     -2.68      1.91
#> 
#> Confidence level used: 0.95
emmeans(m2F, ~ am, mode = "linear.predictor")
#>  am emmean    SE  df asymp.LCL asymp.UCL
#>   0  0.284 0.796 Inf     -1.27      1.84
#>   1  0.383 1.172 Inf     -1.91      2.68
#> 
#> Results are averaged over the levels of: cut 
#> Results are given on the logit (not the response) scale. 
#> Confidence level used: 0.95
emmeans(m2F, ~ am, mode = "exc.prob")
#>  am exc.prob     SE  df asymp.LCL asymp.UCL
#>   0    0.483 0.0509 Inf     0.383     0.583
#>   1    0.477 0.0677 Inf     0.344     0.610
#> 
#> Results are averaged over the levels of: cut 
#> Confidence level used: 0.95
emmeans(m2F, ~ am, mode = "prob")
#>  am  prob SE  df asymp.LCL asymp.UCL
#>   0 0.333  0 Inf     0.333     0.333
#>   1 0.333  0 Inf     0.333     0.333
#> 
#> Results are averaged over the levels of: cyl 
#> Confidence level used: 0.95
emmeans(m2F, ~ am, mode = "mean.class")
#>  am mean.class    SE  df asymp.LCL asymp.UCL
#>   0       1.97 0.102 Inf      1.77      2.17
#>   1       1.95 0.135 Inf      1.69      2.22
#> 
#> Confidence level used: 0.95
```

## Support of multivariate emmeans

(I don't think this is crucial...)

Each response is supported separately, but not together:

```R
# Not all resps are predicted by all terms
mMV <- brm(bf(mpg ~ am + disp) + bf(hp ~ disp), 
           data = mtcars,
           chains = 2, iter = 200, refresh = 0)
#> Setting 'rescor' to TRUE by default for this model

ref_grid(mMV, resp = "hp")
#> 'emmGrid' object with variables:
#>     disp = 230.72

ref_grid(mMV)
#> Error : Argument 'resp' must be a single variable name when applying this method to a multivariate model.
#> Error in ref_grid(mMV) : Perhaps a 'data' or 'params' argument is needed
```

But emmeans does support in a way:

``` r
mMVF <- lm(cbind(mpg, hp) ~ disp, data = mtcars)
emmeans::ref_grid(mMVF)
#> 'emmGrid' object with variables:
#>     disp = 230.72
#>     rep.meas = multivariate response levels: mpg, hp
```

**Comment by paul-buerkner** [comment]
Thank you! ordinal models in emmeans is discussed in a separate issue (#980) and I cannot address it fully yet. I was thinking though that the current behavior at least corresponded to one of the existing modes, strange. I will look into it.

What is the advantages of looking at multiple response variables jointly in emmeans as compared to looking at them separately?

**Comment by paul-buerkner** [comment]
The output of the ordinal model completely ignores the intercepts/thresholds at the moment (as is currently intended although not desired behavior). Because of the scale of the predictor variable `mpg`, the predictions without intercepts are very far away from 0, but the difference between the two values of `am` should remain valid.

**Comment by mattansb** [comment]
> The output of the ordinal model completely ignores the intercepts/thresholds at the moment

I think this too should be explicitly mentioned in the docs.
Maybe even emm_basis can give a little warning if an ordinal model is used.

> What is the advantages of looking at multiple response variables jointly in emmeans as compared to looking at them separately?

The only case I can think of is the multivariate parameterization of a rmANOVA, where one would want to compare between the variates (as "levels").
But other than that, nothing crucial really.

**Comment by paul-buerkner** [comment]
Good point. I will add a warning that the current implementation for ordinal models is considered experimental.

**Comment by mattansb** [comment]
### Issue with non-linear 

```R
library(brms)
library(emmeans)


f <- brmsformula(mpg ~ A ^ hp,
                 A ~ cyl, nl = TRUE)

get_prior(f, data = mtcars)
m <- brm(f, data = mtcars,
         prior = prior(normal(0, 3), nlpar = A))


ref_grid(m, nlpar = "A")
#> 'emmGrid' object with variables:
#>     cyl = 6.1875

emmeans(m, nlpar = "A",
        ~ cyl)
#>   cyl emmean lower.HPD upper.HPD
#>  6.19   0.51    -0.636     0.755
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95
```

However, with `epred = TRUE`, we get an error (this does not happen without any nl-components):

```R
ref_grid(m, epred = TRUE)
#> 'emmGrid' object with variables:
#>   hp = 146.69
#>   cyl = 6.1875
#> mpg = response variable with mean 20.091


emmeans(m, epred = TRUE,
        ~ hp + cyl)
#> Error in x@post.beta %*% t(x@linfct[, use, drop = FALSE]) : 
#>   non-conformable arguments
```

**Comment by mattansb** [comment]
Another issue when using `y | subset(i)` in the formula:

```R
mtcars2 <- transform(mtcars,
                     hp = replace(hp, sample(length(hp), size = 6), NA),
                     hasNA = is.na(hp))

library(brms)
library(emmeans)

f <- bf(mpg | subset(!hasNA) ~ hp) + 
  bf(disp ~ cyl + hp) + 
  set_rescor(FALSE)

m <- brm(f, data = mtcars2)

ref_grid(m, resp = "mpg")
#> Error in ctrfn(levels(x), contrasts = contrasts) : 
#>   contrasts not defined for 0 degrees of freedom

ref_grid(m, resp = "disp")
#> Error in ctrfn(levels(x), contrasts = contrasts) : 
#>   contrasts not defined for 0 degrees of freedom
```

Also in a univariate model:
```R
m2 <- brm(mpg | subset(!hasNA) ~ hp, data = mtcars2)
ref_grid(m2)
#> Error in ctrfn(levels(x), contrasts = contrasts) : 
#>   contrasts not defined for 0 degrees of freedom
```

**Comment by mattansb** [comment]
@paul-buerkner Would you like me to log these in a separate issue?

**Comment by paul-buerkner** [comment]
Thanks for identifying these problems. I agree that perhaps it would be safer to log them in a separate issue to make sure I solve all of them before next release.

**Pull request merged**
