### PR TITLE
Reduce sum

### PR DESCRIPTION
**Pull request by paul-buerkner**
This PR adds support for within-chain parallelization via `reduce_sum` (#892). It is ready to be merged as soon as we decide what to do with the detailed demo @wds15 has written.

### CODE REVIEW

**Comment by paul-buerkner** [comment]
I did some minor cleaning to the vignette and will now merge this PR. Thank you @wds15 for your trenmendous amount of help with getting this done!

**Comment by wds15** [comment]
Oh...you are very welcome! It’s awesome to have this thing now in brms which will make it readily available in an easy and time efficient way which is really import in practice. Time is a huge constraint and saving on modeler time with brms is important. Let’s see what users do with this.

**Comment by paul-buerkner** [comment]
I agree! I bet users will ask a lot of questions on discourse :-D

wds15 <notifications@github.com> schrieb am Di., 29. Sept. 2020, 10:29:

**Comment by nahorp** [comment]
Screen Shot 2020-10-02 at 6 19 20 am

Hello,

I was trying to read the latest `reduce_sum` based vignette but I can't find that vignette via that link. Are vignettes there only updated once the changes are on CRAN?

Thank you

**Comment by paul-buerkner** [comment]
You can find it here:
https://github.com/paul-buerkner/brms/blob/master/doc/brms_threading.html

Am Do., 1. Okt. 2020 um 22:20 Uhr schrieb Rohan Puri <
notifications@github.com>:

**Pull request merged**
