### PR TITLE
Fix class definition removed from ‘dbplyr’ #issue 1356

### PR DESCRIPTION
**Pull request by munoztd0**
added  Matrix (>= 1.4.0), to dependencies to fix class definition removed class with tidyverse

### CODE REVIEW

**Comment by paul-buerkner** [comment]
Thanks! Much appreciated!

**Comment by paul-buerkner** [comment]
But why does it have to be under depends? Wouldn't imports be enough? Things in depends are automatically loaded into the environment when loading brms which is not ideal as it clutters the environment with a lot of function.

**Comment by munoztd0** [comment]
I totally agree but that must be an issue with tidyverse_conflicts() I'm affraid

**Comment by paul-buerkner** [comment]
I see. Thank you! I will think of that a little bit and see if some other options come up that avoids putting it under depends.

**Comment by paul-buerkner** [comment]
I think this issue was resolved outside of brms. Closing this now. Thank your for your time and effort you put into finding a solution from the brms side!

**Pull request closed without merging**
