### PR TITLE
Export and update validate_prior()

### PR DESCRIPTION
**Pull request by hsbadr**
`validate_prior` validates priors supplied by the user and it can be a better alternative to set priors, similar to the defaults generated by `get_prior`.

- [X] Exported `validate_prior` and updated the manual.
- [X] Used `formula` argument for better user interface.
- [X] Exposed the arguments for special priors.
- [X] Updated and cleaned up the arguments.
- [X] Updated roxygenized man/docs.

## Example:

```
library(brms)

priors <- validate_prior(
  c(
    prior_string("normal(0,10)", class = "b"),
    prior(normal(1,2), class = b, coef = treat),
    prior_(~cauchy(0,2), class = ~sd, group = ~subject, coef = ~Intercept)
  ),
  formula = brmsformula(
    rating ~ treat + period + carry + (1|subject),
    family = cumulative()
  ),
  data = inhaler,
  sample_prior = "no"
)

knitr::kable(priors)
```

> |prior                |class     |coef      |group   |resp |dpar |nlpar |bound |source  |
> |:--------------------|:---------|:---------|:-------|:----|:----|:-----|:-----|:-------|
> |normal(0,10)         |b         |          |        |     |     |      |      |user    |
> |                     |b         |carry     |        |     |     |      |      |default |
> |                     |b         |period    |        |     |     |      |      |default |
> |normal(1, 2)         |b         |treat     |        |     |     |      |      |user    |
> |student_t(3, 0, 2.5) |Intercept |          |        |     |     |      |      |default |
> |student_t(3, 0, 2.5) |sd        |          |        |     |     |      |      |default |
> |                     |sd        |          |subject |     |     |      |      |default |
> |cauchy(0, 2)         |sd        |Intercept |subject |     |     |      |      |user    |
>

### CODE REVIEW

**Comment by paul-buerkner** [comment]
Thank you for opening this PR! I am not yet sure if I want to expose the `validate_prior` interface as it may contain non-stable parts. For example, the fact that `...` is passed to the internal functions `validate_prior_special` is currently not ideal for a user facing function. Ideas are much appreciated.

**Comment by hsbadr** [comment]
> Thank you for opening this PR! I am not yet sure if I want to expose the `validate_prior` interface as it may contain non-stable parts. For example, the fact that `...` is passed to the internal functions `validate_prior_special` is currently not ideal for a user facing function. Ideas are much appreciated.

I see. `validate_prior` is already used by `brm`, `make_stancode` and `make_standata`. Exposing it would make it easier to test by the users. As for the `...`, I can't see anything except `require_nlpar_prior ` passed by  `validate_prior` in the current version of the code, but we can expose the arguments and add sanity checks. If you agree, I can work on this.

**Comment by hsbadr** [comment]
We may also label it [Lifecycle: experimental](https://www.tidyverse.org/lifecycle/#experimental) and recommend using `get_priors` for the time being.

**Comment by paul-buerkner** [comment]
I need to think of this a bit more of whether I like the existing interface of `validate_prior` in order to expose it. Give me a few days.

**Comment by hsbadr** [comment]
@paul-buerkner Should we close this? It seems that you want to improve the `validate_prior` interface before exposing it.

**Comment by paul-buerkner** [comment]
No leave it open please. I am just overwhelmed by too much stuff right now and will get back to it once I have the time.

**Comment by hsbadr** [comment]
> No leave it open please. I am just overwhelmed by too much stuff right now and will get back to it once I have the time.

I've updated and cleaned up the arguments.

Before, the last commits, it was randomly crashing R:
```r
 *** caught segfault ***
address 0x6, cause 'memory not mapped'

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```

**Comment by hsbadr** [comment]
> No leave it open please. I am just overwhelmed by too much stuff right now and will get back to it once I have the time.

I've updated and cleaned up the arguments.

Before the last commits, it was randomly crashing R:
```r
 *** caught segfault ***
address 0x6, cause 'memory not mapped'

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```

**Comment by paul-buerkner** [comment]
I made some edits to the PR which is now ready to be merged. Thank you for moving this issue forward!

**Comment by hsbadr** [comment]
Thanks @paul-buerkner! I'll test this ASAP and let you know if I run into any related issues.

**Pull request merged**
