### PR TITLE
Add option to drop normalizing constants

### PR DESCRIPTION
**Pull request by andrjohns**
This PR adds the option to use density functions that exclude normalizing constants (i.e., ```normal_lupdf```), to reduce unnecessary computation in the evaluation of the model likelihood (as covered in issue #1017).

As an example, given the following test model:
```
make_stancode(
    count ~ zAge + zBase * Trt + (1|patient) + (1|obs),
    data = epilepsy, family = poisson(),
    prior = prior(student_t(5,0,10), class = b) +
        prior(cauchy(0,2), class = sd)
)
```

When calling the model with ```normalize = TRUE``` (the default), the ```model``` block evaluates to the expected:
```
model {
  // likelihood including all constants
  if (!prior_only) {
    // initialize linear predictor term
    vector[N] mu = Intercept + rep_vector(0.0, N);
    for (n in 1:N) {
      // add more terms to the linear predictor
      mu[n] += r_1_1[J_1[n]] * Z_1_1[n] + r_2_1[J_2[n]] * Z_2_1[n];
    }
    target += poisson_log_glm_lpmf(Y | Xc, mu, b);
  }
  // priors including all constants
  target += student_t_lpdf(b | 5, 0, 10);
  target += student_t_lpdf(Intercept | 3, 1.4, 2.5);
  target += cauchy_lpdf(sd_1 | 0, 2)
    - 1 * cauchy_lccdf(0 | 0, 2);
  target += std_normal_lpdf(z_1[1]);
  target += cauchy_lpdf(sd_2 | 0, 2)
    - 1 * cauchy_lccdf(0 | 0, 2);
  target += std_normal_lpdf(z_2[1]);
}
```

When calling the test model with ```normalize = FALSE```, the model block then evaluates to:
```
model {
  // likelihood not including constants
  if (!prior_only) {
    // initialize linear predictor term
    vector[N] mu = Intercept + rep_vector(0.0, N);
    for (n in 1:N) {
      // add more terms to the linear predictor
      mu[n] += r_1_1[J_1[n]] * Z_1_1[n] + r_2_1[J_2[n]] * Z_2_1[n];
    }
    target += poisson_log_glm_lupmf(Y | Xc, mu, b);
  }
  // priors not including constants
  target += student_t_lupdf(b | 5, 0, 10);
  target += student_t_lupdf(Intercept | 3, 1.4, 2.5);
  target += cauchy_lupdf(sd_1 | 0, 2);
  target += std_normal_lupdf(z_1[1]);
  target += cauchy_lupdf(sd_2 | 0, 2);
  target += std_normal_lupdf(z_2[1]);
}
```

This is also compatible with ```reduce_sum```/```threading```:
```
  // compute partial sums of the log-likelihood
  // Use _lpmf suffix for unnormalized densities
  real partial_log_lik_lpmf(int[] seq, int start, int end, int[] Y, matrix Xc, vector b, real Intercept, int[] J_1, vector Z_1_1, vector r_1_1, int[] J_2, vector Z_2_1, vector r_2_1) {
    real ptarget = 0;
    int N = end - start + 1;
    // initialize linear predictor term
    vector[N] mu = Intercept + rep_vector(0.0, N);
    for (n in 1:N) {
      // add more terms to the linear predictor
      int nn = n + start - 1;
      mu[n] += r_1_1[J_1[nn]] * Z_1_1[nn] + r_2_1[J_2[nn]] * Z_2_1[nn];
    }
    ptarget += poisson_log_glm_lupmf(Y[start:end] | Xc[start:end], mu, b);
    return ptarget;
  }
```

But note that ```partial_log_lik``` function now has a ```_lpmf``` suffix, due to restrictions with how the ```_lupdf```/```_lupmf``` functions can be called (see [this Stanc3 issue for more info/background](https://github.com/stan-dev/stanc3/issues/753)).

### CODE REVIEW

**Comment by andrjohns** [comment]
There are two areas in this code that I could use your perspective on. To avoid the parsing replacing the ```lpdf```/```lpmf``` suffixes on brms distributions (i.e., ```dirichlet_logit```), I've just put a list of distributions that should not have their suffixes replaced in the ```stan_likelihood``` file. This is definitely not the most elegant approach, so if you have a better idea then I'm on board. Otherwise, can you check that I haven't missed any distributions?

I also haven't added any functionality to check that the user is calling the ```cmdstanr``` backend with ```normalize=FALSE```, since there doesn't seem to be a similar check for threading, and I thought there should be a unified approach.

**Comment by rok-cesnovar** [comment]
Nice, did you observe how much of a speedup this produced?

**Comment by andrjohns** [comment]
I haven't done much proper benchmarking, but some rough testing shows good results. Using the above ```poisson``` model and scaling up the dataset (by just replicating it) shows roughly a 25% speedup:
```
library(brms)

data("epilepsy")

epilepsy2 = purrr::map_dfr(1:4,~(epilepsy))

fit1 = brm(
    count ~ zAge + zBase * Trt + (1|patient) + (1|obs),
    data = epilepsy2, family = poisson(),
    prior = prior(student_t(5,0,10), class = b) +
        prior(cauchy(0,2), class = sd), cores=4,
    backend = "cmdstanr", normalize = TRUE
)

fit2 = brm(
    count ~ zAge + zBase * Trt + (1|patient) + (1|obs),
    data = epilepsy2, family = poisson(),
    prior = prior(student_t(5,0,10), class = b) +
        prior(cauchy(0,2), class = sd), cores=4,
    backend = "cmdstanr", normalize = FALSE
)

> colMeans(rstan::get_elapsed_time(fit1$fit))
  warmup   sample 
20.96475 21.43675 
> colMeans(rstan::get_elapsed_time(fit2$fit))
  warmup   sample 
15.61725 15.00700 
```

**Comment by paul-buerkner** [comment]
Thank you for your work on this issue! I have made some edits and now I think the only thing that is missing are unit tests. Do you have time to add a few to `tests/testthat/tests.make_stancode`? No worries if not. In this case, I will add them.

**Comment by andrjohns** [comment]
Thanks for adding me as a contributor! 

Yep I can add those unit tests tomorrow

**Comment by andrjohns** [comment]
Hey Paul was just adding those unit tests and noticed that you removed the addition of the ```_lpmf``` suffix for ```partial_log_lik``` when threading. The un-normalized densities otherwise it throws a parsing error:
```
make_stancode(
    count ~ zAge + zBase * Trt + (1|patient) + (1|obs),
    data = epilepsy, family = poisson(),
    prior = prior(student_t(5,0,10), class = b) +
        prior(cauchy(0,2), class = sd),
    normalize = FALSE, threads = threading(2),
    parse = T, backend="cmdstanr"
)

Semantic error in '/tmp/RtmpQWJBHz/filece268ce8de.stan', line 28, column 15 to column 73:
   -------------------------------------------------
    26:        mu[n] += r_1_1[J_1[nn]] * Z_1_1[nn] + r_2_1[J_2[nn]] * Z_2_1[nn];
    27:      }
    28:      ptarget += poisson_log_glm_lupmf(Y[start:end] | Xc[start:end], mu, b);
                        ^
    29:      return ptarget;
    30:    }
   -------------------------------------------------

Functions with names ending in _lupdf and _lupmf can only be used in the model block or user-defined functions with names ending in _lpdf, _lpmf or _lp.

Error: Syntax error found! See the message above for more information.
```

Can you add that back in or should I?

**Comment by paul-buerkner** [comment]
Oh now I see why you added them. Shall we perhaps always add that suffix
then I stead of making it conditional?

Andrew Johnson <notifications@github.com> schrieb am Mo., 7. Dez. 2020,
12:48:

**Comment by paul-buerkner** [comment]
Perhaps just add _lpdf in any case?

Paul Buerkner <paul.buerkner@gmail.com> schrieb am Mo., 7. Dez. 2020, 12:50:

**Comment by andrjohns** [comment]
Yeah I think having the suffix by default would be the easiest. The parser will require that it has the ```_lpmf``` suffix since the first argument is an array of integers (so Stanc3 assumes an integer outcome). Good for me to add that when I push the tests?

**Comment by paul-buerkner** [comment]
Yes, please go ahead and add it back. Sorry for inducing confusion by removing it. I should have asked first and then forgot...

**Comment by andrjohns** [comment]
No worries! Just pushed the tests and fixed threading. I also found that user-specified custom families weren't working (their suffixes were also getting un-normalized) so I fixed those as well. The framework you put in place for checking whether to normalize made it pretty quick!

**Comment by paul-buerkner** [comment]
Thanks! I am reading the PR again right now and run some checks. Is there anything you want to add before we merge this PR?

**Comment by andrjohns** [comment]
Nope it's all good with me!

**Comment by paul-buerkner** [comment]
Merging now. Thank you again for your contribution! :-)

**Comment by wds15** [comment]
Apologies if I missed this, but is this normalize=FALSE feature now available for cmdstanr **and** rstan (2.21)? Does brms still work with this feature with rstan 2.21 - or what happens if a user calls normalize=FALSE but is using rstan 2.21?

(I want to suggest to a colleague to use this feature for his Poisson / NegBinomial model where this makes a difference)

**Comment by andrjohns** [comment]
No the ```lupdf``` extensions were only introduced in 2.25 so they're not available in RStan yet, ```brms``` errors if you try it.

**Comment by wds15** [comment]
Ok, great. That makes sense. So at the moment only cmdstanr backend supports normalize=FALSE is what this means. Good.

**Comment by storopoli** [comment]
Looking forward to put it into practice. Thank you!

**Comment by paul-buerkner** [comment]
This could be added. Please open a new issue for that so that I don't forget about it.

**Pull request merged**
