### PR TITLE
Fix workflow failures

### PR DESCRIPTION
**Pull request by andrjohns**
Add `cmdstanr` installation to workflow setup to fix dependency errors

### CODE REVIEW

**Comment by andrjohns** [comment]
Yep it's just struggling because cmdstanr isn't on CRAN. I'm debugging on my fork (so I don't clog up your notifications!), I've just about got it sorted

**Comment by andrjohns** [comment]
Quick update - I've figured out how to handle the cmdstanr install, which also identified that some of the tests were failing because of the addition of the code canonicaliser in #1304 means that the reference values for some of the `make_stancode` tests were no longer accurate.

I've fixed those issues and now I'm just chasing down some failures while building vignettes on Windows

**Comment by andrjohns** [comment]
@paul-buerkner Sorry about the false start, this is all good to go now

**Comment by paul-buerkner** [comment]
Thank you!

**Pull request merged**
