### PR TITLE
Multivariate emmeans support

### LINKED ISSUE #1207: emmeans: multivariate support
I know we've discussed this elsewhere, and I know that due to `brms`' complex multivariate modeling it can be difficult to support multivariate models in `emmeans`, but perhaps this support can be extended *only* to models using the `mvbind(y1, y2) ~ x1 + x2` formulation?

### PR DESCRIPTION
**Pull request by paul-buerkner**
This PR aims to close #1207 

@mattansb I don't think this current version is correct yet. Can you please review and test it and provide feedback? 

For example, are `bhat` and `V` computed correctly, that is, after flattening `post.beta`?

Right now, emmeans only gives me only a single estimate across responses but I would have (naively perhaps) expected one estimate per response.

Reprex:

```R
df <- data.frame(y1 = rnorm(100), y2= rnorm(100), x1 = rnorm(100), x2 = rnorm(100))
fit <- brm(mvbind(y1,y2) ~ x1+x2, df)

library(emmeans)
emmeans(fit, "x1")
```

### CODE REVIEW

**Comment by mattansb** [comment]
@paul-buerkner thanks!
I'll take a closer look at the code next week and see what still needs to be done.

**Comment by mattansb** [comment]
I gave the wrong computation of `X`, should always be `diag(ncol(post.beta))` on the final `post.beta`, so just take that part out of the `if`:

```R
  if (is.mvbrmsterms(bterms)) {
    dims <- dim(post.beta)
    post.beta <- matrix(post.beta, ncol = prod(dims[2:3]))
    misc$ylevs = list(rep.meas = bterms$responses)
  }
  X <- diag(ncol(post.beta))
```

After that - works right!


```R
library(brms)
library(emmeans)

df <- data.frame(y1 = rnorm(100),
                 y2 = rnorm(100), 
                 x1 = rnorm(100),
                 x2 = rnorm(100))

fit <- brm(mvbind(y1, y2) ~ x1 + x2, df, chains = 1, iter = 1000)
fit.ref <- lm(cbind(y1, y2) ~ x1 + x2, df)



# Default: Collapse over repeated measures:
emmeans(fit, "x1",
        at = list(x1 = c(-1, 1)))
#>  x1  emmean lower.HPD upper.HPD
#>  -1  0.0546    -0.115  0.245706
#>   1 -0.1733    -0.382 -0.000126
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95

emmeans(fit.ref, "x1",
        at = list(x1 = c(-1, 1)))
#>  x1  emmean     SE df lower.CL upper.CL
#>  -1  0.0602 0.0992 97   -0.137   0.2572
#>   1 -0.1783 0.1010 97   -0.379   0.0223
#> 
#> Results are averaged over the levels of: rep.meas 
#> Confidence level used: 0.95





# Ask for MV with rep.meas
emmeans(fit, c("x1", "rep.meas"),
        at = list(x1 = c(-1, 1)))
 x1 rep.meas  emmean lower.HPD upper.HPD
#>  -1 y1       -0.0440    -0.313    0.2025
#>   1 y1       -0.3123    -0.590   -0.0418
#>  -1 y2        0.1511    -0.121    0.4243
#>   1 y2       -0.0351    -0.293    0.2330
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95


emmeans(fit.ref, c("x1", "rep.meas"),
        at = list(x1 = c(-1, 1)))
#>  x1 rep.meas  emmean    SE df lower.CL upper.CL
#>  -1 y1       -0.0369 0.140 97   -0.314   0.2406
#>   1 y1       -0.3144 0.142 97   -0.597  -0.0319
#>  -1 y2        0.1573 0.139 97   -0.119   0.4334
#>   1 y2       -0.0422 0.142 97   -0.323   0.2388
#> 
#> Confidence level used: 0.95 
```

**Comment by paul-buerkner** [comment]
Brilliant, thank you! One more question: Right now I allow multivariate models only if they have the same family and link function. Do you know if emmeans support different families and/or link functions in multivariate models?

**Comment by mattansb** [comment]
Yeah, that sounds like the right thing to do here...
emmeans does not allow for different links (or families) - behind the scenes, the different variates are treated as "levels" of a factor called "rep.meas", so not much flexibility there.

**Comment by paul-buerkner** [comment]
Thanks. Good to know we are not missing out on a feature then. Will make the change later on today and then merge.

**Comment by paul-buerkner** [comment]
Done. Before I merge, I will add some slight additions to support categorical and mixture models. I will do that tomorrow.

**Comment by paul-buerkner** [comment]
I have refactored the code a bit more so that adding even further emmeans support should be easier in the future. Anyway, multvariate models are working and I will merge this PR now. Thank you very much for your help!

**Comment by mattansb** [comment]
Thank *you*!

Do you have a time-line yet on when this can be expected on CRAN?

**Comment by paul-buerkner** [comment]
I will aim for next week.

Mattan S. Ben-Shachar ***@***.***> schrieb am Mo., 9. Aug.
2021, 13:03:

**Pull request merged**
