### PR TITLE
Support cmdstanr as additional backend

### PR DESCRIPTION
**Pull request by paul-buerkner**
The PR implements cmdstanr as additional backend (#891). It should stay open until brms is CRAN releasable either because cmdstanr itself is on CRAN or if we found another way to make this possible (see https://github.com/stan-dev/cmdstanr/issues/168).

### CODE REVIEW

**Comment by paul-buerkner** [comment]
Tagging @jgabry and @mitzimorris

**Comment by jgabry** [comment]
Looks good!

**Comment by paul-buerkner** [comment]
Although cmdstanr is not on CRAN yet, I will merge this PR into master now. If the next brms CRAN release needs to happen before cmdstanr gets on CRAN, I will either make my own package repo (https://github.com/stan-dev/cmdstanr/issues/168) or comment out the cmdstanr requiring functions for the release (which is easy due to the chosen modularization).

**Comment by jgabry** [comment]
Awesome!

> I will either make my own package repo ([stan-dev/cmdstanr#168](https://github.com/stan-dev/cmdstanr/issues/168)) or comment out the cmdstanr requiring functions for the release (which is easy due to the chosen modularization).

Maybe by then we'll also have that Stan R package repository that @rok-cesnovar suggested on discourse

**Pull request merged**
