### PR TITLE
Approximate Gaussian Processes

### PR DESCRIPTION
**Pull request by paul-buerkner**
This PR implementes approximate Gaussian processes as discussed in #540.

@avehtari, @gabriuma, @MichaelRiis anything you want me to add or change before I merge this PR?

### CODE REVIEW

**Comment by gabriuma** [comment]
Some thoughts:
Due to symmetry of the input space can not be guaranteed, even it is mean centered, I think we should define L=c*max(abs(x)). The X-label of the figure could also be changed by rho/max(abs(x)), or something like that.
Although c=5/2 can be appropriate for many datasets, there will be many others where this will not. From the different experiments I've done, I noticed some sensitivity to the choice of c, which can lead to long computational times and poor results.
I think some a priori guess of the lengthscale would be interesting and then, setting the factor c looking at the figure. (Maybe some iterative process would also be interesting to think about).
In the multivariate case, when the lengthscale is significantly different in each dimension, it would also be interesting to set different L and M for each dimension in order to improve the performance. We are working on that.

**Comment by avehtari** [comment]
Before we understand L and c better, this is better to be labeled as experimental and possible that something will change. It's good idea now to require user to make choices.

**Comment by paul-buerkner** [comment]
Ok. A follow up on this. Would you be opposed to using the term `L` as the multiplicative factor in brms (at least user facing), instead of `c` as the latter is a commonly used function in R?

**Comment by gabriuma** [comment]
It is probably better not to use the letter L as notation for the factor c,
in order to be coherent with the related literature. Any other appropiate
notation for the factor c would be fine, I think. Then, we can change the
label in the figure accordingly.

**Comment by paul-buerkner** [comment]
Thanks! Upon further thinking about it, I think it's ok to just use `c`. I will change the accordingly

**Comment by paul-buerkner** [comment]
Would an upper-case `C` work for you as well?

**Comment by paul-buerkner** [comment]
Sorry for the back and forth. I decided that lower-case `c` is ok even if the base combine function has the same name (they won't mask each other so it doesn't matter). That is, we can continue to use the your case study notation when working with brms.

**Comment by gabriuma** [comment]
I meant that 'C' seems good for me.

**Comment by paul-buerkner** [comment]
thanks for the clarification. Indeed, I was unsure between C and c but then decided to use the latter for immediate consistency with the case studies. I will merge this PR now, but we still have roughly a month before the next CRAN release which gives us plenty of time to change argument names, defaults, etc.

**Pull request merged**
