### PR TITLE
Zombie fix attempts

### LINKED ISSUE #1658: brms::log_lik creating zombies if cmdstanr is loaded
Originally issue reported at https://github.com/n-kall/priorsense/issues/48, but now reporting here as this has been narrowed done to `brms`

Minimal example by @n-kall
```
m <- brms::brm(yield ~ 1, npk, backend = "rstan")
brms::log_lik(m) # no zombies

library(cmdstanr)
brms::log_lik(m) # creates zombies
```

I checked that the zombies are created by the line https://github.com/paul-buerkner/brms/blob/298b947fa9cfb914aeb7cb3aab7974aa179682b1/R/log_lik.R#L127

### PR DESCRIPTION
**Pull request by paul-buerkner**
In this PR, I will try several things to fix #1658. @avehtari or @n-kall I would be gratefull if you could check it out on your systems because I currently don't have access to Ubuntu.

List of things tried out in this PR so far:

- [x] copy the `plapply` code directly into `log_lik` (don't call `plapply` itself anymore)
- [x] always use PSOCK clusters even on unix systems

### CODE REVIEW

**Comment by n-kall** [comment]
I think that first try fixed it. I don't seem to get zombies with the minimal example anymore. @avehtari how about you?

**Comment by avehtari** [comment]
Using the github master I didn't get zombies with the minimal example, but after running at least 333 lines of brms_demo.R I get zombies when calling `brms::log_lik()` also with this PR

**Comment by paul-buerkner** [comment]
thanks! is any of the code executed in parallel? and where can I found the
brms_demo.R?

Aki Vehtari ***@***.***> schrieb am Mi., 13. Nov. 2024, 18:45:

**Comment by avehtari** [comment]
A new minimal example in the issue

**Comment by paul-buerkner** [comment]
Thanks. Okay, here is my next try. It contains two changes.

First, log_lik will not longer automatically use the `mc.cores` option for now, but only use parallel execution if cores is explicitely specified in `log_lik`. That is, your latest example

```R
library(brms)
options(brms.backend = "cmdstanr", mc.cores = 2)

m0 <- brms::brm(yield ~ 0, npk, refresh=0)
ll<-brms::log_lik(m0) # no zombies

m1 <- brms::brm(yield ~ 1, npk, refresh=0)
ll<-brms::log_lik(m1) # yes zombies
```

will now almost surely not created zombies anymore simply because parallel execution of `log_lik` is not enabled via `options(mc.cores = 2)` anymore.

However, 

```R
library(brms)
options(brms.backend = "cmdstanr", mc.cores = 2)

m0 <- brms::brm(yield ~ 0, npk, refresh=0, cores = 2)
ll<-brms::log_lik(m0) # no zombies

m1 <- brms::brm(yield ~ 1, npk, refresh=0, cores = 2)
ll<-brms::log_lik(m1) # yes zombies
```

may still created zombies. In an attempt to "solve" this as well I now force the user of PSOCK clusters in `plapply`. Perhaps when using PSOCK clusters, zombies will no longer occur? This is what I would like you to try out with the latest version of the log-lik-zombies branch.

**Comment by n-kall** [comment]
I confirm that with master and previous fix, @avehtari's new minimal example was producing zombies.
Now with the new patch, zombies are not created even if I add cores = 2 or cores = 16 to the brm call or the log_lik call, and I do see additional R processes spawning as expected

**Comment by n-kall** [comment]
Using `cores` argument seems to cause an error with the `rstan` backend though:

```r
devtools::load_all()
options(brms.backend = "rstan")

m0 <- brms::brm(yield ~ 0, npk, refresh = 0)
ll<-brms::log_lik(m0) # no zombies

m1 <- brms::brm(yield ~ 1, npk, refresh = 0, mc.cores = 4, cores = 4)
#> Error in x@mode :
#>   no applicable method for `@` applied to an object of class "try-error"
#> In addition: Warning message:
#> In parallel::mclapply(1:chains, FUN = callFun, mc.preschedule = FALSE,  :
#>   4 function calls resulted in an error
```

**Comment by paul-buerkner** [comment]
you seem to be passing cores twice

Noa Kallioinen ***@***.***> schrieb am Do., 14. Nov. 2024,
08:15:

**Comment by avehtari** [comment]
No more zombies (cmdstanr/rstan) with
```
m0 <- brms::brm(yield ~ 0, npk, refresh=0)
ll<-brms::log_lik(m0, cores=4) 

m1 <- brms::brm(yield ~ 1, npk, refresh=0)
ll<-brms::log_lik(m1, cores=4) 
```
I can also see 4 cores being used.

Also brms_demo.R does not produce zombies, but I guess it is now using just one core for log_lik computations inside powerscaling

**Comment by paul-buerkner** [comment]
Lovely, thank you both! I will clean up the PR and then merge :-)

**Comment by paul-buerkner** [comment]
Merged now :-)

**Pull request merged**
