### PR TITLE
Tests for equivalence of `sratio()` and `cratio()` in case of symmetric distribution functions

### PR DESCRIPTION
**Pull request by fweber144**
This is the PR for enumeration points 4 and 5 of [this comment](https://github.com/paul-buerkner/brms/pull/1137#issuecomment-832596346) (see also [this comment](https://github.com/paul-buerkner/brms/pull/1137#issuecomment-832659592) for an explanation why I commented out the tests for the equivalence of `sratio()` and `cumulative()` in case of the cloglog link).

### CODE REVIEW

**Comment by paul-buerkner** [comment]
Thanks for opening this PR! I would prefer these tests to live in `tests/local/tests.models_new.R` (or some new file in `/local` because all the example models are stored and shipped with brms thus further increasing the package size. Would that be possible?

**Comment by fweber144** [comment]
Sure, I'll check that. I wasn't 100% sure if I put everything at the correct (or most appropriate) place.

Another remark: Commit d9266cc is just a leftover fragment from some of my local code. I thought that additional unit test could not harm (especially because it doesn't need a new fit, so it's computationally inexpensive), but if you don't want it, just remove it. In any case, it's not complete (as it only tests the `sratio()` family).

**Comment by fweber144** [comment]
I now moved `brmsfit_example7` (and a copy of `brmsfit_example4`) as well as the corresponding test to `tests/local/tests.models_new.R`. Is it OK this way?

**Comment by paul-buerkner** [comment]
Great! Can you remove the commented out cloglog tests please? I don't really want this to be in the code base at the moment even if commented out.

**Comment by paul-buerkner** [comment]
I removed the commented-out tests and will merge this PR after checks are passing locally.

**Comment by fweber144** [comment]
Thanks! Sorry for not replying—I was just away from my computer.

**Comment by paul-buerkner** [comment]
no worries :-)

Am Do., 6. Mai 2021 um 16:29 Uhr schrieb Frank Weber <
***@***.***>:

**Pull request merged**
