### PR TITLE
initial support for OpenCL

### PR DESCRIPTION
**Pull request by paul-buerkner**
adds support for OpenCL #1166. @rok-cesnovar would you mind reviewing this PR? I didn't have time to activate OpenCL on my own machine so weren't able to test the implementation myself

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
On it! Thanks!

**Review by rok-cesnovar — APPROVED** [review]
Looks great!

Tried with the following:
```
library(brms)

n <- 30000
k <- 10
X <- matrix(rnorm(n * k), ncol = k)
y <- rbinom(n, size = 1, prob = plogis(10 * X[,1] + 9 * X[,2] + 8 * X[,3] + 7 * X[,4] + 6 * X[,5] + 5 * X[,6] + 4 * X[,7] + 3 * X[,8] + 2 * X[,9] + 2 * X[,10] + 1))

brmsfit <- brm(
    y ~ X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + X10,
    data = data.frame(y, X),
    family = bernoulli(),
    backend = "cmdstanr",
    opencl = opencl(ids = c(0, 0)),
    cores = 4
)
```

And it uses the GPU. Via the stanfit object one can verify a device was used with:

```r
> brmsfit$fit@stan_args[[1]]$opencl_platform_name
[1] "AMDAcceleratedParallelProcessing"
> brmsfit$fit@stan_args[[1]]$opencl_device_name
[1] "gfx906+sram-ecc"
```

Also tried with other IDs and it picked up the CPU as well.

**Comment by rok-cesnovar** [comment]
I hope to have some time in June to work on a vignette if you think it would be useful?

**Comment by paul-buerkner** [comment]
Thank you! Yes, I think a vignette would be very useful!

**Comment by paul-buerkner** [comment]
cool. what needs to be added to the rstan calls inside brms to activate
opencl?

Hamada S. Badr ***@***.***> schrieb am Fr., 28. Mai 2021,
00:28:

**Comment by hsbadr** [comment]
> what needs to be added to the rstan calls inside brms to activate opencl?

Nothing different from `cmdstanr` for `brms` side, but `rstan` needs to conditionally set the required compiler flags (or add the definitions at the top of the generated C++ code):
```r
  OPENCL_DEVICE_ID ?= 0
  OPENCL_PLATFORM_ID ?= 0

  CPPFLAGS_OPENCL ?= -DSTAN_OPENCL -DOPENCL_DEVICE_ID=$(OPENCL_DEVICE_ID) -DOPENCL_PLATFORM_ID=$(OPENCL_PLATFORM_ID)
  CPPFLAGS_OPENCL += -DCL_HPP_TARGET_OPENCL_VERSION=120 -DCL_HPP_MINIMUM_OPENCL_VERSION=120
  CPPFLAGS_OPENCL += -DCL_HPP_ENABLE_EXCEPTIONS -Wno-ignored-attributes
  CXXFLAGS_OPENCL ?= -I $(OPENCL)
```
and link to `OpenCL` or handle the linking flags:
```r
  ifeq ($(OS),Darwin)
    LDLIBS_OPENCL ?= -framework OpenCL
  else
    LDLIBS_OPENCL ?= -lOpenCL
  endif
```

@andrjohns was testing it [here](https://github.com/stan-dev/rstan/issues/899#issuecomment-773839343), and I think he needed to link properly to `OpenCL`. @andrjohns: any updates on this?

**Comment by andrjohns** [comment]
I wasn't able to get the linking to work unfortunately, but I didn't test too deeply. I was on a deadline to get some models re-run so I ended up just using cmdstanr

**Comment by hsbadr** [comment]
Thanks for the update. We might need to let `rstan` link to `OpenCL` R package and define `STAN_OPENCL`, but I think that explicitly linking to the system OpenCL, with `LDFLAGS`, should fix the error you get. I'll try to test OpenCL on one of my machines.

**Pull request merged**
