### PR TITLE
projpred: Pass `fit_elapsed_time` to `init_refmodel`

### PR DESCRIPTION
**Pull request by paul-buerkner**
As discussed in #1136

### CODE REVIEW

**Comment by paul-buerkner** [comment]
Just a note that `brms:::elapsed_time` now also works with cmdstanr and defaults to `NULL` if no information is provided (not `NA`). I think `NULL` would also be a better default for that information in projpred.

**Comment by paul-buerkner** [comment]
@fweber144 Do you know if this PR is still relevant for something that will be implemented in projpred in the future?

**Comment by fweber144** [comment]
Yes, for projpred's `workflow` branch.

**Comment by paul-buerkner** [comment]
@fweber144 Any updates on this?

**Comment by fweber144** [comment]
I don't think the `workflow` branch will be merged into `master` (because `workflow` is quite outdated now), but that doesn't mean that some of its features couldn't be re-implemented in `master`. Especially the timings (for which this PR is relevant) might be something that @avehtari is interested in, right?

**Comment by paul-buerkner** [comment]
I will close this PR for the time being. It's such a minor change we can do it directly on main whenever this feature makes it into projpred.

**Pull request closed without merging**
